name: Healthhelper
version: 1
main: com.henry.healthhelper.Healthhelper
api-version: 1.19
description: minecraft health plugin
commands:
  heal:
    description: heals player to max health
    usage: /<command>
    aliases: heal
  feed:
    description: makes players saturation 20
    usage: /<command>
    aliases: feed
  clearNegitiveEffects:
    description: clears all negative effects
    usage: /<command>
    aliases: [clearnegativeeffects, cleareffects]
  extinguish:
    description: makes you not on fire
      usage: /<command>
      aliases: extinguish
